import pandas as pd
import os
import sys
import datetime

# Configuration
EXCEL_PATH = os.path.join("source", "requirements_app_PEGS.xlsx")
OUTPUT_ADOC = "output.adoc"

# Ordre d'affichage des chapitres
CATEGORY_ORDER = ["Goals", "Environment", "System", "Project"]

def clean_text(text):
    if pd.isna(text):
        return ""
    # On garde les sauts de ligne avec le format AsciiDoc " +"
    return str(text).strip().replace("\n", " +\n")

def get_priority_icon(moscow):
    m = str(moscow).upper().strip()
    if m == 'MUST': return "🔴 *MUST*"
    if m == 'SHOULD': return "🟠 *SHOULD*"
    if m == 'COULD': return "🟢 *COULD*"
    if m == 'WONT': return "⚪ *WON'T*"
    return m

def generate_asciidoc():
    print(f"🔍 Recherche du fichier : {EXCEL_PATH}")
    
    if not os.path.exists(EXCEL_PATH):
        print(f"❌ Erreur : Fichier introuvable à {EXCEL_PATH}")
        sys.exit(1)

    try:
        df = pd.read_excel(EXCEL_PATH)
        if 'Category' in df.columns:
            df['Category'] = df['Category'].str.capitalize()
    except Exception as e:
        print(f"❌ Erreur lecture Excel : {e}")
        sys.exit(1)

    # --- 1. EN-TÊTE ---
    today = datetime.date.today()
    adoc_content = f"""= Project Requirements Document
:author: Generated by GitHub Actions
:revdate: {today}
:doctype: book
:toc: macro
:toc-title: Table des matières
:toclevels: 3
:sectnums:
:sectnumlevels: 4
:icons: font
:experimental:
:source-highlighter: highlight.js
:imagesdir: images

toc::[]

== Introduction

Ce document contient les spécifications du projet générées automatiquement.

[TIP]
====
Dernière mise à jour : {today}
Source des données : `{os.path.basename(EXCEL_PATH)}`
====
"""

    # --- 2. TRAITEMENT DES CATÉGORIES ---
    if 'Category' not in df.columns:
        df['Category'] = 'General'
        categories_to_process = ['General']
    else:
        existing_categories = df['Category'].unique().tolist()
        ordered_categories = [c for c in CATEGORY_ORDER if c in existing_categories]
        remaining_categories = [c for c in existing_categories if c not in ordered_categories]
        categories_to_process = ordered_categories + remaining_categories

    for category in categories_to_process:
        items = df[df['Category'] == category]
        if 'ID' in items.columns:
            items = items.sort_values(by='ID')

        adoc_content += f"\n== {category}\n\n"
        
        for _, row in items.iterrows():
            req_id = clean_text(row.get('ID', 'REQ-???'))
            title = clean_text(row.get('Title', 'Sans titre'))
            moscow = clean_text(row.get('MoSCoW', ''))
            desc = clean_text(row.get('Description', ''))
            rationale = clean_text(row.get('Rationale', ''))
            accept_crit = clean_text(row.get('Acceptance Criteria', ''))
            status = clean_text(row.get('Status', ''))

            priority_display = get_priority_icon(moscow)
            
            # Titre de l'exigence (Niveau 3) -> Apparaît dans la TOC
            adoc_content += f"=== {req_id}: {title}\n\n"
            
            # Métadonnées
            adoc_content += f"**Priorité:** {priority_display} | **Statut:** `{status}`\n\n"
            
            # Description : On utilise du gras (**) et un saut de ligne (+)
            # Ce n'est plus un titre, donc invisible dans la TOC
            if desc:
                adoc_content += f"**Description** +\n{desc}\n\n"
            
            # Justification (Reste dans un bloc note pour la lisibilité, invisible dans la TOC)
            if rationale:
                adoc_content += f"[NOTE]\n.Justification\n====\n{rationale}\n====\n\n"
            
            # Critères : Idem, gras + saut de ligne
            if accept_crit:
                adoc_content += f"**Critères d'acceptation** +\n{accept_crit}\n\n"
            
            # Séparateur visuel
            adoc_content += "---\n\n"

    # --- 3. SORTIE ---
    with open(OUTPUT_ADOC, "w", encoding="utf-8") as f:
        f.write(adoc_content)
    
    print(f"🎉 Succès : {OUTPUT_ADOC} généré.")

if __name__ == "__main__":
    generate_asciidoc()