import pandas as pd
import os
import sys
import datetime

# Configuration
EXCEL_PATH = os.path.join("source", "requirements_app_PEGS.xlsx")
OUTPUT_ADOC = "output.adoc"

def clean_text(text):
    if pd.isna(text):
        return ""
    # On échappe les caractères spéciaux AsciiDoc si nécessaire, mais on garde les sauts de ligne
    return str(text).strip().replace("\n", " +\n")

def get_priority_icon(moscow):
    """Retourne une icône ou un style selon la priorité"""
    m = str(moscow).upper().strip()
    if m == 'MUST':
        return "🔴 *MUST*"
    elif m == 'SHOULD':
        return "🟠 *SHOULD*"
    elif m == 'COULD':
        return "🟢 *COULD*"
    elif m == 'WONT':
        return "⚪ *WON'T*"
    return m

def generate_asciidoc():
    print(f"🔍 Recherche du fichier : {EXCEL_PATH}")
    
    if not os.path.exists(EXCEL_PATH):
        print(f"❌ Erreur : Fichier introuvable à {EXCEL_PATH}")
        sys.exit(1)

    try:
        df = pd.read_excel(EXCEL_PATH)
        # On trie pour avoir un ordre logique : Catégorie puis ID
        if 'ID' in df.columns and 'Category' in df.columns:
            df = df.sort_values(by=['Category', 'ID'])
    except Exception as e:
        print(f"❌ Erreur lecture Excel : {e}")
        sys.exit(1)

    # --- 1. EN-TÊTE (HEADER) ---
    # C'est ici qu'on définit le style "Book" du template
    today = datetime.date.today()
    adoc_content = f"""= Project Requirements Document
:author: Generated by GitHub Actions
:revdate: {today}
:doctype: book
:toc: left
:toclevels: 3
:sectnums:
:sectnumlevels: 4
:icons: font
:experimental:
:source-highlighter: highlight.js
:imagesdir: images

// Introduction standard du template
== Introduction

Ce document contient les spécifications du projet générées automatiquement.

[TIP]
====
Dernière mise à jour : {today}
Source des données : `{os.path.basename(EXCEL_PATH)}`
====
"""

    # --- 2. GÉNÉRATION DU CONTENU ---
    
    # Groupement par Catégorie (Project, System, Hardware, etc.)
    # Si la colonne n'existe pas, on met tout dans "General"
    if 'Category' not in df.columns:
        df['Category'] = 'General'

    for category, items in df.groupby('Category'):
        adoc_content += f"\n== {category}\n\n"
        
        for _, row in items.iterrows():
            req_id = clean_text(row.get('ID', 'REQ-???'))
            title = clean_text(row.get('Title', 'Sans titre'))
            moscow = clean_text(row.get('MoSCoW', ''))
            desc = clean_text(row.get('Description', ''))
            rationale = clean_text(row.get('Rationale', ''))
            accept_crit = clean_text(row.get('Acceptance Criteria', ''))
            status = clean_text(row.get('Status', ''))

            priority_display = get_priority_icon(moscow)
            
            # Structure "Exigence" propre
            adoc_content += f"=== {req_id}: {title}\n\n"
            
            # Bloc de métadonnées (Tableau sans bordure ou Sidebar)
            adoc_content += f"**Priorité:** {priority_display} | **Statut:** `{status}`\n\n"
            
            # La description principale dans un bloc sidebar
            if desc:
                adoc_content += f".Description\n****\n{desc}\n****\n\n"
            
            # Justification en Note
            if rationale:
                adoc_content += f"[NOTE]\n.Justification\n====\n{rationale}\n====\n\n"
            
            # Critères d'acceptation en exemple ou citation
            if accept_crit:
                adoc_content += f".Critères d'acceptation\n[example]\n====\n{accept_crit}\n====\n\n"
            
            adoc_content += "---\n\n"

    # --- 3. ÉCRITURE DU FICHIER ---
    with open(OUTPUT_ADOC, "w", encoding="utf-8") as f:
        f.write(adoc_content)
    
    print(f"🎉 Succès : {OUTPUT_ADOC} généré selon le template Book.")

if __name__ == "__main__":
    generate_asciidoc()