import pandas as pd
import os
import sys
import datetime

# Configuration
EXCEL_PATH = os.path.join("source", "requirements_app_PEGS.xlsx")
OUTPUT_ADOC = "output.adoc"

# L'ordre précis que tu as demandé
CATEGORY_ORDER = ["Goals", "Environment", "System", "Project"]

def clean_text(text):
    if pd.isna(text):
        return ""
    return str(text).strip().replace("\n", " +\n")

def get_priority_icon(moscow):
    m = str(moscow).upper().strip()
    if m == 'MUST': return "🔴 *MUST*"
    if m == 'SHOULD': return "🟠 *SHOULD*"
    if m == 'COULD': return "🟢 *COULD*"
    if m == 'WONT': return "⚪ *WON'T*"
    return m

def generate_asciidoc():
    print(f"🔍 Recherche du fichier : {EXCEL_PATH}")
    
    if not os.path.exists(EXCEL_PATH):
        print(f"❌ Erreur : Fichier introuvable à {EXCEL_PATH}")
        sys.exit(1)

    try:
        df = pd.read_excel(EXCEL_PATH)
        # Normalisation des catégories (Majuscule au début) pour matcher la liste
        if 'Category' in df.columns:
            df['Category'] = df['Category'].str.capitalize()
    except Exception as e:
        print(f"❌ Erreur lecture Excel : {e}")
        sys.exit(1)

    # --- 1. EN-TÊTE (HEADER) ---
    today = datetime.date.today()
    adoc_content = f"""= Project Requirements Document
:author: Generated by GitHub Actions
:revdate: {today}
:doctype: book
:toc: macro
:toc-title: Table des matières
:toclevels: 3
:sectnums:
:sectnumlevels: 4
:icons: font
:experimental:
:source-highlighter: highlight.js
:imagesdir: images

// Placement manuel de la TOC ici
toc::[]

== Introduction

Ce document contient les spécifications du projet générées automatiquement.

[TIP]
====
Dernière mise à jour : {today}
Source des données : `{os.path.basename(EXCEL_PATH)}`
====
"""

    # --- 2. GÉNÉRATION DU CONTENU PAR ORDRE DÉFINI ---
    
    # On vérifie d'abord que la colonne existe
    if 'Category' not in df.columns:
        print("⚠️ Attention: Colonne 'Category' manquante. Tout sera mis dans 'General'.")
        df['Category'] = 'General'
        categories_to_process = ['General']
    else:
        # On commence par ta liste, puis on ajoute les autres catégories trouvées (s'il y en a)
        existing_categories = df['Category'].unique().tolist()
        # On filtre ta liste pour ne garder que ce qui existe vraiment dans l'Excel
        ordered_categories = [c for c in CATEGORY_ORDER if c in existing_categories]
        # On ajoute à la fin les catégories qui seraient dans l'Excel mais pas dans ta liste (ex: Hardware)
        remaining_categories = [c for c in existing_categories if c not in ordered_categories]
        
        categories_to_process = ordered_categories + remaining_categories

    for category in categories_to_process:
        # Récupération des lignes pour cette catégorie
        items = df[df['Category'] == category]
        
        # On trie par ID à l'intérieur de la catégorie
        if 'ID' in items.columns:
            items = items.sort_values(by='ID')

        adoc_content += f"\n== {category}\n\n"
        
        for _, row in items.iterrows():
            req_id = clean_text(row.get('ID', 'REQ-???'))
            title = clean_text(row.get('Title', 'Sans titre'))
            moscow = clean_text(row.get('MoSCoW', ''))
            desc = clean_text(row.get('Description', ''))
            rationale = clean_text(row.get('Rationale', ''))
            accept_crit = clean_text(row.get('Acceptance Criteria', ''))
            status = clean_text(row.get('Status', ''))

            priority_display = get_priority_icon(moscow)
            
            adoc_content += f"=== {req_id}: {title}\n\n"
            adoc_content += f"**Priorité:** {priority_display} | **Statut:** `{status}`\n\n"
            
            if desc:
                adoc_content += f".Description\n****\n{desc}\n****\n\n"
            
            if rationale:
                adoc_content += f"[NOTE]\n.Justification\n====\n{rationale}\n====\n\n"
            
            if accept_crit:
                adoc_content += f".Critères d'acceptation\n[example]\n====\n{accept_crit}\n====\n\n"
            
            adoc_content += "---\n\n"

    # --- 3. ÉCRITURE ---
    with open(OUTPUT_ADOC, "w", encoding="utf-8") as f:
        f.write(adoc_content)
    
    print(f"🎉 Succès : {OUTPUT_ADOC} généré (Ordre: {', '.join(categories_to_process)})")

if __name__ == "__main__":
    generate_asciidoc()